version: 0.1
phases:
  install:
    runtime-versions:
        java: openjdk8
    commands:
      - mvn package
      - aws cloudformation package --template-file template.yaml --s3-bucket sam-local-java --output-template-file template-export.yaml
artifacts:
  type: zip
  files:
    - template-export.yaml
